name: peekaboo
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A sample program to experiment with Linux adjtimex() system call
description: |
  A sample program to experiment with Linux adjtimex() system call

grade: devel
confinement: strict
base: core20

apps:
  peekaboo:
    command: bin/peekaboo
    daemon: simple
    plugs: [time-control]

parts:
  peekaboo:
    plugin: make
    source: src/peekaboo
